CREATE TABLE USERS
(
    USERNAME    VARCHAR(31)     NOT NULL,
    EMAIL       VARCHAR(254)    NOT NULL,
    PASSWORD    CHAR(64)        NOT NULL,
    PRIMARY KEY(USERNAME)
    -- SHA-256 FOR PASSWORDS
);

CREATE TABLE LISTS
(
    ID          INT UNSIGNED    NOT NULL,
    NAME        VARCHAR(255)    NOT NULL,
    CATEGORY    VARCHAR(31)     NOT NULL,
    DESCRIPTION TEXT,

    CREATOR     VARCHAR(31)     NOT NULL,

    PRIMARY KEY(ID),
    FOREIGN KEY(CREATOR) REFERENCES USERS(USERNAME) ON DELETE CASCADE
);

CREATE TABLE ELEMENTS
(
    ID          INT UNSIGNED    NOT NULL,
    NAME        VARCHAR(255)    NOT NULL,
    URL         VARCHAR(2083),

    LIST        INT UNSIGNED    NOT NULL,

    PRIMARY KEY(ID),
    FOREIGN KEY(LIST) REFERENCES LISTS(ID) ON DELETE CASCADE
);

CREATE TABLE COMMENTS
(
    ID          INT UNSIGNED    NOT NULL,
    COMMENT     TEXT            NOT NULL,
    USER        VARCHAR(31)     NOT NULL,
    LIST        INT UNSIGNED    NOT NULL,

    PRIMARY KEY(ID),
    FOREIGN KEY(USER) REFERENCES USERS(USER) ON DELETE CASCADE,
    FOREIGN KEY(LIST) REFERENCES LISTS(ID) ON DELETE CASCADE

);

CREATE TABLE RATINGS
(
    RATING      TINYINT         NOT NULL,
    USER        VARCHAR(31)     NOT NULL,
    ELEMENT     INT UNSIGNED    NOT NULL,

    PRIMARY KEY(USER,ELEMENT),
    FOREIGN KEY(USER) REFERENCES USERS(USER) ON DELETE CASCADE,
    FOREIGN KEY(ELEMENT) REFERENCES ELEMENTS(ID) ON DELETE CASCADE

);

CREATE TABLE SUBSCRIPTIONS
(
    USER        VARCHAR(31)     NOT NULL,
    LIST        INT UNSIGNED    NOT NULL,

    PRIMARY KEY(USER,LIST),
    FOREIGN KEY(USER) REFERENCES USERS(USER) ON DELETE CASCADE,
    FOREIGN KEY(LIST) REFERENCES LISTS(ID) ON DELETE CASCADE
);